This phase focuses on implementing the XGBoost algorithm, an advanced ensemble learning technique known for its high accuracy and efficiency. The model will be trained and evaluated for both regression and classification tasks, followed by a comparison with the previously developed Linear Regression, Logistic Regression, and Random Forest models to identify the best-performing model for AirPulse AI.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from xgboost import XGBClassifier
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [ ]:
df = pd.read_csv(f"E:\AirPulse AI\Files\data\processed_air_quality.csv")
df.head()

,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,temperature,humidity,wind_speed,hour,day,month,aqi
0,1.450487,0.519719,0.674688,-1.420657,0.562469,1.551509,-0.293566,0.205112,0.301189,1.180454,-0.316142,0.660868,-0.568606,0.939010,-1.784835,0.0,108
1,1.450487,0.519719,0.674688,-1.420657,-0.469550,-0.284383,0.294120,-0.820666,-0.302941,1.096537,-1.648118,1.187285,1.344121,1.083473,-1.784835,0.0,90
2,1.450487,0.519719,0.674688,-1.420657,0.106583,0.496056,-0.370482,1.426839,-1.655143,0.704924,1.085556,0.268974,1.592513,1.227936,-1.784835,0.0,84
3,1.450487,0.519719,0.674688,-1.420657,-0.564751,0.391971,2.277869,0.641006,-1.116764,-2.280128,0.171387,1.668330,1.339379,1.372399,-1.784835,0.0,158
4,1.450487,0.519719,0.674688,-1.420657,-1.092887,-0.149177,0.502292,0.359915,-0.163882,1.136497,-0.828489,0.996830,-0.462100,1.516862,-1.784835,0.0,97

# Regression with XGBoost

In [ ]:
X = df.drop("aqi", axis=1)
y = df["aqi"]

# Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train XGBoost Regressor

In [ ]:
xgb_reg = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

xgb_reg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

# Prediction

In [ ]:
xgb_pred = xgb_reg.predict(X_test)

# Evaluate Regression

In [ ]:
xgb_mae = mean_absolute_error(y_test, xgb_pred)

xgb_rmse = np.sqrt(
    mean_squared_error(y_test, xgb_pred)
)

xgb_r2 = r2_score(y_test, xgb_pred)

print("MAE :", xgb_mae)
print("RMSE:", xgb_rmse)
print("R² :", xgb_r2)

MAE : 0.6286355257034302
RMSE: 1.3617692667727594
R² : 0.9968728423118591

# Compare Regression Models

In [ ]:
lr = LinearRegression()

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_mae = mean_absolute_error(y_test, lr_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))
lr_r2 = r2_score(y_test, lr_pred)

               Model        MAE       RMSE  R2 Score
0  Linear Regression  11.980532  14.889226  0.626160
1      Random Forest   0.084883   0.573011  0.999446
2            XGBoost   0.628636   1.361769  0.996873